name: Run Sales System Tests

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
        working-directory: sales-system
      - run: npm test
        working-directory: sales-system
      - run: npm run build
        working-directory: sales-system

